name: unitTestsValidation

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit -c phpunit.xml
